// domain/repositories/repository.tokens.ts

export const TRANSPORT_COMPANY_REPOSITORY =
  Symbol('TRANSPORT_COMPANY_REPOSITORY');

export const USER_REPOSITORY =
  Symbol('USER_REPOSITORY');

export const SUBSCRIPTION_PLAN_REPOSITORY = Symbol(
  'SUBSCRIPTION_PLAN_REPOSITORY',
);

export const SUBSCRIPTION_ORDER_REPOSITORY = Symbol(
  'SUBSCRIPTION_ORDER_REPOSITORY',
);

export const PAYMENT_RECEIPT_REPOSITORY = Symbol(
  'PAYMENT_RECEIPT_REPOSITORY',
);

export const SUBSCRIPTION_REPOSITORY = Symbol(
  'SUBSCRIPTION_REPOSITORY',
);

export const RECEIPT_ANALYZER = Symbol(
  'RECEIPT_ANALYZER',
);

export const TELEGRAM_LINK_REPOSITORY =
  Symbol('TELEGRAM_LINK_REPOSITORY');