import { MigrationInterface, QueryRunner } from "typeorm";

export class InitialTransport1789675824877 implements MigrationInterface {
    name = 'InitialTransport1789675824877'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE "TrailerType" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "title" character varying(100) NOT NULL, "code" character varying(50) NOT NULL, "recordStatus" smallint NOT NULL DEFAULT '0', CONSTRAINT "UQ_b21eb623c285507839d9e286a4a" UNIQUE ("code"), CONSTRAINT "PK_d2fd1f39016f3844e11e3cb6e5e" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "Trailer" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "trailerTypeId" uuid NOT NULL, "plate" character varying(30) NOT NULL, "capacityKg" numeric(12,2) NOT NULL, "verificationStatus" smallint NOT NULL DEFAULT '0', "recordStatus" smallint NOT NULL DEFAULT '0', "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_ad37c9d1dedb2b18e445436b8d1" UNIQUE ("plate"), CONSTRAINT "PK_eef1a5b1d30323c135f0a1ae718" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "Location" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "title" character varying(200), "provinceId" uuid, "cityId" uuid, "address" text, "postalCode" character varying(20), "latitude" numeric(10,7), "longitude" numeric(10,7), "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_d0125e359cde2707aec388b9c59" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "Province" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying(100) NOT NULL, "code" character varying(20), "recordStatus" smallint NOT NULL DEFAULT '0', CONSTRAINT "UQ_0092bd7c119c5f7367d9210fae5" UNIQUE ("code"), CONSTRAINT "PK_bfd94a1f97ddca1a17e68dfce96" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "City" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "provinceId" uuid NOT NULL, "name" character varying(100) NOT NULL, "code" character varying(20), "latitude" numeric(10,7), "longitude" numeric(10,7), "recordStatus" smallint NOT NULL DEFAULT '0', CONSTRAINT "PK_1c5a287828771160a6e703cd37e" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "DriverAvailability" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "driverId" uuid NOT NULL, "vehicleId" uuid, "trailerId" uuid, "availableFrom" TIMESTAMP NOT NULL, "availableUntil" TIMESTAMP, "originCityId" uuid, "preferredDestinationCityId" uuid, "currentLatitude" numeric(10,7), "currentLongitude" numeric(10,7), "minimumFreightAmount" numeric(18,2), "status" smallint NOT NULL DEFAULT '0', "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_316981ad58839e9bcd05acb798b" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_59d2e870119ad891adb76cb65e" ON "DriverAvailability" ("availableFrom", "availableUntil") `);
        await queryRunner.query(`CREATE INDEX "IDX_ed1a46edb0810f93e42cd258a4" ON "DriverAvailability" ("originCityId", "status") `);
        await queryRunner.query(`CREATE INDEX "IDX_15ba759542bacc2d362babed19" ON "DriverAvailability" ("driverId", "status") `);
        await queryRunner.query(`CREATE TABLE "CargoType" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "title" character varying(150) NOT NULL, "code" character varying(50) NOT NULL, "isHazardous" boolean NOT NULL DEFAULT false, "requiresRefrigeration" boolean NOT NULL DEFAULT false, "recordStatus" smallint NOT NULL DEFAULT '0', "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_c26d32b38bfb7ac735b5bbe38ce" UNIQUE ("code"), CONSTRAINT "PK_d85f01e4d50147f78121322af07" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "DriverMatch" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "loadId" uuid NOT NULL, "driverId" uuid NOT NULL, "driverAvailabilityId" uuid, "totalScore" numeric(6,2) NOT NULL, "distanceScore" numeric(6,2) NOT NULL DEFAULT '0', "vehicleScore" numeric(6,2) NOT NULL DEFAULT '0', "trailerScore" numeric(6,2) NOT NULL DEFAULT '0', "routeScore" numeric(6,2) NOT NULL DEFAULT '0', "reliabilityScore" numeric(6,2) NOT NULL DEFAULT '0', "returnLoadScore" numeric(6,2) NOT NULL DEFAULT '0', "distanceToPickupKm" numeric(10,2), "priceScore" numeric(6,2) NOT NULL DEFAULT '0', "algorithmVersion" character varying(50) NOT NULL, "calculatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_ad2ad37fab07aa82851f1b5e821" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_7e54da371cf64b8c816038efbb" ON "DriverMatch" ("loadId", "driverId") `);
        await queryRunner.query(`CREATE INDEX "IDX_83a87436ed56fb970357a67a82" ON "DriverMatch" ("driverId", "calculatedAt") `);
        await queryRunner.query(`CREATE INDEX "IDX_4f928905db278920a80bea37e9" ON "DriverMatch" ("loadId", "totalScore") `);
        await queryRunner.query(`CREATE TABLE "LoadOffer" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "loadId" uuid NOT NULL, "driverId" uuid NOT NULL, "driverMatchId" uuid, "matchScore" numeric(6,2), "offeredFreightAmount" numeric(18,2), "status" smallint NOT NULL DEFAULT '0', "sentAt" TIMESTAMP NOT NULL DEFAULT now(), "seenAt" TIMESTAMP, "acceptedAt" TIMESTAMP, "rejectedAt" TIMESTAMP, "expiresAt" TIMESTAMP, CONSTRAINT "PK_2cd116aec2ffebe36135554042d" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_37a1a3cd1aa890853a4f0791dd" ON "LoadOffer" ("driverId", "status") `);
        await queryRunner.query(`CREATE INDEX "IDX_54081254b630c4dadd02c57970" ON "LoadOffer" ("loadId", "status") `);
        await queryRunner.query(`CREATE TABLE "DriverLoadRequest" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "loadId" uuid NOT NULL, "driverId" uuid NOT NULL, "vehicleId" uuid, "trailerId" uuid, "requestedFreightAmount" numeric(18,2), "description" text, "status" smallint NOT NULL DEFAULT '0', "requestedAt" TIMESTAMP NOT NULL DEFAULT now(), "reviewedAt" TIMESTAMP, "reviewedBy" uuid, "rejectReason" text, CONSTRAINT "PK_c3a7c1d8f6dbe036cd19cdfec64" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_305b7a04b30de2ebd2cac79320" ON "DriverLoadRequest" ("driverId", "status") `);
        await queryRunner.query(`CREATE INDEX "IDX_2be8b5209f7ce94de505aad240" ON "DriverLoadRequest" ("loadId", "status") `);
        await queryRunner.query(`CREATE TABLE "Route" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "tripId" uuid NOT NULL, "provider" character varying(50), "distanceKm" numeric(12,2) NOT NULL, "durationMinutes" integer NOT NULL, "encodedPolyline" text, "estimatedFuelLiters" numeric(10,2), "estimatedFuelCost" numeric(18,2), "tollCost" numeric(18,2), "estimatedTotalCost" numeric(18,2), "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_4845b605fc62b06c30cd1b66c00" UNIQUE ("tripId"), CONSTRAINT "REL_4845b605fc62b06c30cd1b66c0" UNIQUE ("tripId"), CONSTRAINT "PK_6589597363e6037bb091a597c6f" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "FuelRecord" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "tripId" uuid NOT NULL, "vehicleId" uuid NOT NULL, "driverId" uuid NOT NULL, "liters" numeric(10,2) NOT NULL, "amount" numeric(18,2) NOT NULL, "odometer" numeric(12,2), "latitude" numeric(10,7), "longitude" numeric(10,7), "stationName" character varying(200), "receiptUrl" character varying(500), "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_5a974b8ed2c40de6a14097036d2" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_e9bb661a8e124fd1b5e4c69296" ON "FuelRecord" ("vehicleId", "createdAt") `);
        await queryRunner.query(`CREATE INDEX "IDX_594d6b815ba86b36358bdb771e" ON "FuelRecord" ("tripId", "createdAt") `);
        await queryRunner.query(`CREATE TABLE "TripExpense" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "tripId" uuid NOT NULL, "expenseType" smallint NOT NULL, "amount" numeric(18,2) NOT NULL, "description" text, "receiptUrl" character varying(500), "latitude" numeric(10,7), "longitude" numeric(10,7), "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_b5d274e6d6167922cc5c54f49a6" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_8817633a11bea90898724725e2" ON "TripExpense" ("tripId", "expenseType") `);
        await queryRunner.query(`CREATE TABLE "LoadingOrder" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "tripId" uuid NOT NULL, "orderNumber" character varying(50) NOT NULL, "scheduledLoadingAt" TIMESTAMP, "validUntil" TIMESTAMP, "loadingInstructions" text, "externalReference" character varying(100), "fileUrl" character varying(500), "status" smallint NOT NULL DEFAULT '0', "issuedAt" TIMESTAMP, "issuedBy" uuid, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_5062be1d359615a0fe42286912f" UNIQUE ("tripId"), CONSTRAINT "UQ_f3c18e0c021461aaab8a30f6764" UNIQUE ("orderNumber"), CONSTRAINT "REL_5062be1d359615a0fe42286912" UNIQUE ("tripId"), CONSTRAINT "PK_51b1946a052cc62e5f0ba649f25" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "Waybill" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "tripId" uuid NOT NULL, "waybillNumber" character varying(100) NOT NULL, "senderName" character varying(200) NOT NULL, "receiverName" character varying(200) NOT NULL, "cargoDescription" character varying(250) NOT NULL, "weightKg" numeric(14,2) NOT NULL, "freightAmount" numeric(18,2), "insuranceAmount" numeric(18,2), "issueDate" TIMESTAMP NOT NULL, "externalReference" character varying(100), "fileUrl" character varying(500), "status" smallint NOT NULL DEFAULT '0', "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_2049010616662463be4e8de4266" UNIQUE ("tripId"), CONSTRAINT "UQ_81522ea6b7fac7830f582eb12ad" UNIQUE ("waybillNumber"), CONSTRAINT "REL_2049010616662463be4e8de426" UNIQUE ("tripId"), CONSTRAINT "PK_22264502f767454364984a2746d" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_81522ea6b7fac7830f582eb12a" ON "Waybill" ("waybillNumber") `);
        await queryRunner.query(`CREATE TABLE "DeliveryProof" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "tripId" uuid NOT NULL, "receiverName" character varying(200) NOT NULL, "receiverMobile" character varying(20), "method" smallint NOT NULL, "otpCodeHash" character varying(255), "signatureUrl" character varying(500), "photoUrl" character varying(500), "latitude" numeric(10,7), "longitude" numeric(10,7), "deliveredAt" TIMESTAMP NOT NULL, "notes" text, "status" smallint NOT NULL DEFAULT '0', "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_4a901d7b58265327dffe3316f8c" UNIQUE ("tripId"), CONSTRAINT "REL_4a901d7b58265327dffe3316f8" UNIQUE ("tripId"), CONSTRAINT "PK_728dd20fda7e83826560852b177" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "Payment" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "settlementId" uuid NOT NULL, "amount" numeric(18,2) NOT NULL, "paymentMethod" smallint NOT NULL, "referenceNumber" character varying(100), "paidAt" TIMESTAMP, "status" smallint NOT NULL DEFAULT '0', "description" text, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_07e9fb9a8751923eb876d57a575" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_d2eb0d5d1d98e784a5a29b84ff" ON "Payment" ("paidAt") `);
        await queryRunner.query(`CREATE INDEX "IDX_b52701997788b3dfbb62a11e3f" ON "Payment" ("settlementId", "status") `);
        await queryRunner.query(`CREATE TABLE "Settlement" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "tripId" uuid NOT NULL, "freightAmount" numeric(18,2) NOT NULL, "companyCharge" numeric(18,2) NOT NULL DEFAULT '0', "insuranceAmount" numeric(18,2) NOT NULL DEFAULT '0', "taxAmount" numeric(18,2) NOT NULL DEFAULT '0', "advancePayment" numeric(18,2) NOT NULL DEFAULT '0', "otherDeductions" numeric(18,2) NOT NULL DEFAULT '0', "driverPayable" numeric(18,2) NOT NULL, "paidAmount" numeric(18,2) NOT NULL DEFAULT '0', "status" smallint NOT NULL DEFAULT '0', "settledAt" TIMESTAMP, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_9ff72bc80c42b4ba0e50381bbc2" UNIQUE ("tripId"), CONSTRAINT "REL_9ff72bc80c42b4ba0e50381bbc" UNIQUE ("tripId"), CONSTRAINT "PK_d353b0ef96863e43f3e26e49df6" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_0bb65bfc6ce2e6838bded045d1" ON "Settlement" ("status") `);
        await queryRunner.query(`CREATE TABLE "TripLocation" ("id" BIGSERIAL NOT NULL, "tripId" uuid NOT NULL, "latitude" numeric(10,7) NOT NULL, "longitude" numeric(10,7) NOT NULL, "speed" numeric(8,2), "heading" numeric(6,2), "accuracy" numeric(8,2), "recordedAt" TIMESTAMP NOT NULL, CONSTRAINT "PK_266ee6c62602a4439450f735970" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_a24143d1685c49447e32f3e2cf" ON "TripLocation" ("recordedAt") `);
        await queryRunner.query(`CREATE INDEX "IDX_faeb841e6500dbfa808f4076d7" ON "TripLocation" ("tripId", "recordedAt") `);
        await queryRunner.query(`CREATE TABLE "Trip" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "tripNumber" character varying(50) NOT NULL, "assignmentId" uuid NOT NULL, "loadId" uuid NOT NULL, "transportCompanyId" uuid NOT NULL, "driverId" uuid NOT NULL, "vehicleId" uuid NOT NULL, "trailerId" uuid, "startedAt" TIMESTAMP, "arrivedPickupAt" TIMESTAMP, "loadingStartedAt" TIMESTAMP, "loadedAt" TIMESTAMP, "departedAt" TIMESTAMP, "arrivedDestinationAt" TIMESTAMP, "deliveredAt" TIMESTAMP, "originOdometer" numeric(12,2), "destinationOdometer" numeric(12,2), "estimatedDistanceKm" numeric(12,2), "actualDistanceKm" numeric(12,2), "estimatedDurationMinutes" integer, "actualDurationMinutes" integer, "estimatedFuelLiters" numeric(10,2), "actualFuelLiters" numeric(10,2), "status" smallint NOT NULL DEFAULT '0', "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_52fedb71f6f7ac18c9f8f5fbf74" UNIQUE ("tripNumber"), CONSTRAINT "UQ_d434995cd2c77a5f9c71db31cb2" UNIQUE ("assignmentId"), CONSTRAINT "REL_d434995cd2c77a5f9c71db31cb" UNIQUE ("assignmentId"), CONSTRAINT "PK_51df3b6625559b1bf9bb6d858c8" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_ca2dc51a970ab5377dfa5da5f0" ON "Trip" ("loadId") `);
        await queryRunner.query(`CREATE INDEX "IDX_e2282ec3b597efae28a86df546" ON "Trip" ("transportCompanyId", "status") `);
        await queryRunner.query(`CREATE INDEX "IDX_d485417dfe0a2ed5b383df4495" ON "Trip" ("driverId", "status") `);
        await queryRunner.query(`CREATE TABLE "LoadAssignment" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "loadId" uuid NOT NULL, "driverId" uuid NOT NULL, "vehicleId" uuid NOT NULL, "trailerId" uuid, "loadOfferId" uuid, "driverLoadRequestId" uuid, "agreedFreightAmount" numeric(18,2), "status" smallint NOT NULL DEFAULT '0', "assignedBy" uuid, "assignedAt" TIMESTAMP NOT NULL DEFAULT now(), "cancelledAt" TIMESTAMP, "cancelledBy" uuid, "cancellationReason" text, "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_4fdef8aee82808a2e6488b3c572" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_c65158539f27cb9d4019917614" ON "LoadAssignment" ("driverId", "status") `);
        await queryRunner.query(`CREATE INDEX "IDX_0a586efb81f36a43162332521d" ON "LoadAssignment" ("loadId", "status") `);
        await queryRunner.query(`CREATE TABLE "RouteOption" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "loadId" uuid NOT NULL, "provider" character varying(50), "distanceKm" numeric(12,2) NOT NULL, "durationMinutes" integer NOT NULL, "estimatedFuelLiters" numeric(10,2), "estimatedFuelCost" numeric(18,2), "tollCost" numeric(18,2), "estimatedTotalCost" numeric(18,2), "score" numeric(6,2), "encodedPolyline" text, "isSelected" boolean NOT NULL DEFAULT false, "calculatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_d46de4c05d5a4abfb08385f1044" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_c37d6d8b80ed3737077db6b09d" ON "RouteOption" ("loadId", "score") `);
        await queryRunner.query(`CREATE TABLE "Load" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "transportRequestId" uuid NOT NULL, "transportCompanyId" uuid NOT NULL, "loadNumber" character varying(50) NOT NULL, "originLocationId" uuid NOT NULL, "destinationLocationId" uuid NOT NULL, "cargoTypeId" uuid NOT NULL, "cargoTitle" character varying(200), "cargoDescription" text, "weightKg" numeric(14,2) NOT NULL, "requiredVehicleTypeId" uuid, "requiredTrailerTypeId" uuid, "loadingFrom" TIMESTAMP, "loadingTo" TIMESTAMP, "deliveryDeadline" TIMESTAMP, "freightAmount" numeric(18,2), "description" text, "status" smallint NOT NULL DEFAULT '0', "publishedAt" TIMESTAMP, "expiresAt" TIMESTAMP, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_cd0c3237987736b270da3f6a130" UNIQUE ("loadNumber"), CONSTRAINT "PK_b0ada674185397913af3ac9cd95" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_cc57638cce12511c5a981f6a00" ON "Load" ("requiredVehicleTypeId", "requiredTrailerTypeId") `);
        await queryRunner.query(`CREATE INDEX "IDX_c342add5fa417877b101f4872b" ON "Load" ("originLocationId", "destinationLocationId") `);
        await queryRunner.query(`CREATE INDEX "IDX_16b681b87e374c663c05a5c56b" ON "Load" ("status", "publishedAt") `);
        await queryRunner.query(`CREATE TABLE "TransportRequest" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "transportCompanyId" uuid NOT NULL, "customerId" uuid NOT NULL, "requestNumber" character varying(50) NOT NULL, "originLocationId" uuid NOT NULL, "destinationLocationId" uuid NOT NULL, "cargoTitle" character varying(200) NOT NULL, "cargoDescription" text, "totalWeightKg" numeric(14,2) NOT NULL, "totalVehicleCount" integer NOT NULL DEFAULT '1', "requiredTrailerTypeId" uuid, "loadingFrom" TIMESTAMP, "loadingTo" TIMESTAMP, "requestedDeliveryAt" TIMESTAMP, "customerPrice" numeric(18,2), "description" text, "status" smallint NOT NULL DEFAULT '0', "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_dc2f1f7a40c8f9fdb52b2102c2f" UNIQUE ("requestNumber"), CONSTRAINT "PK_a4b73e4c775c1d89bd4695f25a0" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "Customer" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "transportCompanyId" uuid NOT NULL, "name" character varying(200) NOT NULL, "type" smallint NOT NULL DEFAULT '1', "nationalId" character varying(20), "economicCode" character varying(30), "contactName" character varying(150), "mobile" character varying(20), "phone" character varying(20), "address" text, "creditLimit" numeric(18,2) NOT NULL DEFAULT '0', "paymentTermDays" integer NOT NULL DEFAULT '0', "recordStatus" smallint NOT NULL DEFAULT '0', "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_60596e16740e1fa20dbf0154ec7" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "TransportCompany" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying(200) NOT NULL, "nationalId" character varying(20), "economicCode" character varying(30), "registrationNo" character varying(30), "phone" character varying(20), "email" character varying(150), "address" text, "latitude" numeric(10,7), "longitude" numeric(10,7), "recordStatus" smallint NOT NULL DEFAULT '0', "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_81b40698bdaa0f4910f1851db44" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "CompanyDriver" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "companyId" uuid NOT NULL, "driverId" uuid NOT NULL, "status" smallint NOT NULL DEFAULT '0', "joinedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_db05c70cf4ac776585080db9bed" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "Driver" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "userId" uuid, "firstName" character varying(100) NOT NULL, "lastName" character varying(100) NOT NULL, "nationalCode" character varying(20) NOT NULL, "mobile" character varying(20) NOT NULL, "birthDate" date, "smartCardNumber" character varying(50), "licenseNumber" character varying(50), "licenseExpireDate" date, "rating" numeric(3,2) NOT NULL DEFAULT '0', "completedTrips" integer NOT NULL DEFAULT '0', "cancelledTrips" integer NOT NULL DEFAULT '0', "verificationStatus" smallint NOT NULL DEFAULT '0', "availabilityStatus" smallint NOT NULL DEFAULT '0', "currentLatitude" numeric(10,7), "currentLongitude" numeric(10,7), "lastLocationAt" TIMESTAMP, "recordStatus" smallint NOT NULL DEFAULT '0', "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_c36e4721fe6a79b75f2d18de2f5" UNIQUE ("nationalCode"), CONSTRAINT "UQ_fb50ff8dfb152c9370d2a38ff91" UNIQUE ("mobile"), CONSTRAINT "PK_9b78eddc1b0c643ec4e956eaac5" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "DriverVehicle" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "driverId" uuid NOT NULL, "vehicleId" uuid NOT NULL, "fromDate" TIMESTAMP NOT NULL, "toDate" TIMESTAMP, "isCurrent" boolean NOT NULL DEFAULT true, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_5e9ced1dd6a93b4c1b6aaa3a409" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "Vehicle" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "vehicleTypeId" uuid NOT NULL, "plate" character varying(30) NOT NULL, "vin" character varying(50), "brand" character varying(100), "model" character varying(100), "year" integer, "capacityKg" numeric(12,2) NOT NULL, "fuelType" smallint, "averageFuelConsumption" numeric(8,2), "verificationStatus" smallint NOT NULL DEFAULT '0', "recordStatus" smallint NOT NULL DEFAULT '0', "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_14e939b073d16afebdb66ac9f3d" UNIQUE ("plate"), CONSTRAINT "UQ_8b2fef92ae708505222dc0b738b" UNIQUE ("vin"), CONSTRAINT "PK_7124b1b9d8e76a0a3dcfc7ed98d" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "VehicleType" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "title" character varying(100) NOT NULL, "code" character varying(50) NOT NULL, "defaultCapacityKg" numeric(12,2), "recordStatus" smallint NOT NULL DEFAULT '0', "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_0afc024b4c5b149c2a5b6b09924" UNIQUE ("code"), CONSTRAINT "PK_03fc220bc4a3090d60fd0ace290" PRIMARY KEY ("id"))`);
        await queryRunner.query(`ALTER TABLE "Trailer" ADD CONSTRAINT "FK_30d1aafa22fce283555bccd47e0" FOREIGN KEY ("trailerTypeId") REFERENCES "TrailerType"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "Location" ADD CONSTRAINT "FK_fd015fc3b566ce57e00ed4bf845" FOREIGN KEY ("provinceId") REFERENCES "Province"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "Location" ADD CONSTRAINT "FK_f6238d75218c0fab06615f8aea2" FOREIGN KEY ("cityId") REFERENCES "City"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "City" ADD CONSTRAINT "FK_bf6142cf9568097619981928455" FOREIGN KEY ("provinceId") REFERENCES "Province"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "DriverAvailability" ADD CONSTRAINT "FK_00d63c1fba313970a74c6f05469" FOREIGN KEY ("driverId") REFERENCES "Driver"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "DriverAvailability" ADD CONSTRAINT "FK_b0c2cc6955e4d63d4584f5ca8cf" FOREIGN KEY ("vehicleId") REFERENCES "Vehicle"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "DriverAvailability" ADD CONSTRAINT "FK_5b782049bfad845bc9ce5872a32" FOREIGN KEY ("trailerId") REFERENCES "Trailer"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "DriverAvailability" ADD CONSTRAINT "FK_24bd372e34986c9b340f9f1cb83" FOREIGN KEY ("originCityId") REFERENCES "City"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "DriverAvailability" ADD CONSTRAINT "FK_451890eae7849347232f474af7b" FOREIGN KEY ("preferredDestinationCityId") REFERENCES "City"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "DriverMatch" ADD CONSTRAINT "FK_69f60292447c83b1585b4c51b25" FOREIGN KEY ("loadId") REFERENCES "Load"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "DriverMatch" ADD CONSTRAINT "FK_9173fa974b603c23e1350c09471" FOREIGN KEY ("driverId") REFERENCES "Driver"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "DriverMatch" ADD CONSTRAINT "FK_931501ef747293149b2872484a1" FOREIGN KEY ("driverAvailabilityId") REFERENCES "DriverAvailability"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "LoadOffer" ADD CONSTRAINT "FK_c78230559b35bb56b9a2acb7162" FOREIGN KEY ("loadId") REFERENCES "Load"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "LoadOffer" ADD CONSTRAINT "FK_f78aa4d09785066b13cf72fd2bd" FOREIGN KEY ("driverId") REFERENCES "Driver"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "LoadOffer" ADD CONSTRAINT "FK_767b01eba868b762b8c1f976f93" FOREIGN KEY ("driverMatchId") REFERENCES "DriverMatch"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "DriverLoadRequest" ADD CONSTRAINT "FK_b4712d22592c0f5ca74961fc6f3" FOREIGN KEY ("loadId") REFERENCES "Load"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "DriverLoadRequest" ADD CONSTRAINT "FK_9052d08be85dfbf0e3da05279cc" FOREIGN KEY ("driverId") REFERENCES "Driver"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "DriverLoadRequest" ADD CONSTRAINT "FK_4bdb6250463f8f2943ad4f0bb87" FOREIGN KEY ("vehicleId") REFERENCES "Vehicle"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "DriverLoadRequest" ADD CONSTRAINT "FK_6150f6f5b1369ce8cdb01292caa" FOREIGN KEY ("trailerId") REFERENCES "Trailer"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "Route" ADD CONSTRAINT "FK_4845b605fc62b06c30cd1b66c00" FOREIGN KEY ("tripId") REFERENCES "Trip"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "FuelRecord" ADD CONSTRAINT "FK_0fa3e2d0869c8672f64e89ccff3" FOREIGN KEY ("tripId") REFERENCES "Trip"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "FuelRecord" ADD CONSTRAINT "FK_a686d07e208488c86f3e29e2cea" FOREIGN KEY ("vehicleId") REFERENCES "Vehicle"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "FuelRecord" ADD CONSTRAINT "FK_649ae27008d8bd334fa9aec183a" FOREIGN KEY ("driverId") REFERENCES "Driver"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "TripExpense" ADD CONSTRAINT "FK_9f0149e3ffe8caf9461813934c3" FOREIGN KEY ("tripId") REFERENCES "Trip"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "LoadingOrder" ADD CONSTRAINT "FK_5062be1d359615a0fe42286912f" FOREIGN KEY ("tripId") REFERENCES "Trip"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "Waybill" ADD CONSTRAINT "FK_2049010616662463be4e8de4266" FOREIGN KEY ("tripId") REFERENCES "Trip"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "DeliveryProof" ADD CONSTRAINT "FK_4a901d7b58265327dffe3316f8c" FOREIGN KEY ("tripId") REFERENCES "Trip"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "Payment" ADD CONSTRAINT "FK_0d14a4ef0d89b5d6f86d79aee5b" FOREIGN KEY ("settlementId") REFERENCES "Settlement"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "Settlement" ADD CONSTRAINT "FK_9ff72bc80c42b4ba0e50381bbc2" FOREIGN KEY ("tripId") REFERENCES "Trip"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "TripLocation" ADD CONSTRAINT "FK_4276556f330948872d53a9ca3ea" FOREIGN KEY ("tripId") REFERENCES "Trip"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "Trip" ADD CONSTRAINT "FK_d434995cd2c77a5f9c71db31cb2" FOREIGN KEY ("assignmentId") REFERENCES "LoadAssignment"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "Trip" ADD CONSTRAINT "FK_ca2dc51a970ab5377dfa5da5f03" FOREIGN KEY ("loadId") REFERENCES "Load"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "Trip" ADD CONSTRAINT "FK_45d5e197417fc3cf66f9615fb0c" FOREIGN KEY ("transportCompanyId") REFERENCES "TransportCompany"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "Trip" ADD CONSTRAINT "FK_0924c27ba104c6e33a6751c0d9f" FOREIGN KEY ("driverId") REFERENCES "Driver"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "Trip" ADD CONSTRAINT "FK_e6ca78501405de3273030457826" FOREIGN KEY ("vehicleId") REFERENCES "Vehicle"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "Trip" ADD CONSTRAINT "FK_9f8994728a83d5a12b21aebfcc6" FOREIGN KEY ("trailerId") REFERENCES "Trailer"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "LoadAssignment" ADD CONSTRAINT "FK_b00dac203c772e475a83f189a8d" FOREIGN KEY ("loadId") REFERENCES "Load"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "LoadAssignment" ADD CONSTRAINT "FK_07260abdf777176469bcccb8825" FOREIGN KEY ("driverId") REFERENCES "Driver"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "LoadAssignment" ADD CONSTRAINT "FK_c3269a1cf0f0e5919cefa42b991" FOREIGN KEY ("vehicleId") REFERENCES "Vehicle"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "LoadAssignment" ADD CONSTRAINT "FK_3c6b1f40e0d42c86a32b378d026" FOREIGN KEY ("trailerId") REFERENCES "Trailer"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "LoadAssignment" ADD CONSTRAINT "FK_86c06a2ba28ad050bbeb01cfc80" FOREIGN KEY ("loadOfferId") REFERENCES "LoadOffer"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "LoadAssignment" ADD CONSTRAINT "FK_f9ec40a726f805ef9a33fc20c3d" FOREIGN KEY ("driverLoadRequestId") REFERENCES "DriverLoadRequest"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "RouteOption" ADD CONSTRAINT "FK_aba53864339827926b041d92715" FOREIGN KEY ("loadId") REFERENCES "Load"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "Load" ADD CONSTRAINT "FK_d108ea11b35539f91a54fff4f91" FOREIGN KEY ("transportRequestId") REFERENCES "TransportRequest"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "Load" ADD CONSTRAINT "FK_3fff981cb944e6dff0104b8cf8b" FOREIGN KEY ("transportCompanyId") REFERENCES "TransportCompany"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "Load" ADD CONSTRAINT "FK_e7cf1b95b8f7bc007cd37417df4" FOREIGN KEY ("originLocationId") REFERENCES "Location"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "Load" ADD CONSTRAINT "FK_26cd728cd3488f2b6e36dbfd7f3" FOREIGN KEY ("destinationLocationId") REFERENCES "Location"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "Load" ADD CONSTRAINT "FK_d29a13d568bfad90b2cd553183f" FOREIGN KEY ("cargoTypeId") REFERENCES "CargoType"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "Load" ADD CONSTRAINT "FK_b50b613ca1f049b092fe21e1b4d" FOREIGN KEY ("requiredVehicleTypeId") REFERENCES "VehicleType"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "Load" ADD CONSTRAINT "FK_ad621df551b450b32b28436a750" FOREIGN KEY ("requiredTrailerTypeId") REFERENCES "TrailerType"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "TransportRequest" ADD CONSTRAINT "FK_33ead42e83a56cec680cde624e3" FOREIGN KEY ("transportCompanyId") REFERENCES "TransportCompany"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "TransportRequest" ADD CONSTRAINT "FK_417aaeda324c186363e902b7cf6" FOREIGN KEY ("customerId") REFERENCES "Customer"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "TransportRequest" ADD CONSTRAINT "FK_09ee52b2bc7cad27dbd86c8207f" FOREIGN KEY ("originLocationId") REFERENCES "Location"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "TransportRequest" ADD CONSTRAINT "FK_4aaa297f48ea8a058ba89fb6e01" FOREIGN KEY ("destinationLocationId") REFERENCES "Location"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "TransportRequest" ADD CONSTRAINT "FK_07d08b39a2e1a722401af71d6a3" FOREIGN KEY ("requiredTrailerTypeId") REFERENCES "TrailerType"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "Customer" ADD CONSTRAINT "FK_ab498703afc4676279446076dcc" FOREIGN KEY ("transportCompanyId") REFERENCES "TransportCompany"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "CompanyDriver" ADD CONSTRAINT "FK_e41f8155ef3cee0b8aa0a57e4f8" FOREIGN KEY ("companyId") REFERENCES "TransportCompany"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "CompanyDriver" ADD CONSTRAINT "FK_d2beec38b46fc8dce401d106af5" FOREIGN KEY ("driverId") REFERENCES "Driver"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "DriverVehicle" ADD CONSTRAINT "FK_50164b47e0aebc86f29e3857c0e" FOREIGN KEY ("driverId") REFERENCES "Driver"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "DriverVehicle" ADD CONSTRAINT "FK_d21de61eef0013e989baf703ffb" FOREIGN KEY ("vehicleId") REFERENCES "Vehicle"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "Vehicle" ADD CONSTRAINT "FK_d08db56155fb429d189ed887293" FOREIGN KEY ("vehicleTypeId") REFERENCES "VehicleType"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "Vehicle" DROP CONSTRAINT "FK_d08db56155fb429d189ed887293"`);
        await queryRunner.query(`ALTER TABLE "DriverVehicle" DROP CONSTRAINT "FK_d21de61eef0013e989baf703ffb"`);
        await queryRunner.query(`ALTER TABLE "DriverVehicle" DROP CONSTRAINT "FK_50164b47e0aebc86f29e3857c0e"`);
        await queryRunner.query(`ALTER TABLE "CompanyDriver" DROP CONSTRAINT "FK_d2beec38b46fc8dce401d106af5"`);
        await queryRunner.query(`ALTER TABLE "CompanyDriver" DROP CONSTRAINT "FK_e41f8155ef3cee0b8aa0a57e4f8"`);
        await queryRunner.query(`ALTER TABLE "Customer" DROP CONSTRAINT "FK_ab498703afc4676279446076dcc"`);
        await queryRunner.query(`ALTER TABLE "TransportRequest" DROP CONSTRAINT "FK_07d08b39a2e1a722401af71d6a3"`);
        await queryRunner.query(`ALTER TABLE "TransportRequest" DROP CONSTRAINT "FK_4aaa297f48ea8a058ba89fb6e01"`);
        await queryRunner.query(`ALTER TABLE "TransportRequest" DROP CONSTRAINT "FK_09ee52b2bc7cad27dbd86c8207f"`);
        await queryRunner.query(`ALTER TABLE "TransportRequest" DROP CONSTRAINT "FK_417aaeda324c186363e902b7cf6"`);
        await queryRunner.query(`ALTER TABLE "TransportRequest" DROP CONSTRAINT "FK_33ead42e83a56cec680cde624e3"`);
        await queryRunner.query(`ALTER TABLE "Load" DROP CONSTRAINT "FK_ad621df551b450b32b28436a750"`);
        await queryRunner.query(`ALTER TABLE "Load" DROP CONSTRAINT "FK_b50b613ca1f049b092fe21e1b4d"`);
        await queryRunner.query(`ALTER TABLE "Load" DROP CONSTRAINT "FK_d29a13d568bfad90b2cd553183f"`);
        await queryRunner.query(`ALTER TABLE "Load" DROP CONSTRAINT "FK_26cd728cd3488f2b6e36dbfd7f3"`);
        await queryRunner.query(`ALTER TABLE "Load" DROP CONSTRAINT "FK_e7cf1b95b8f7bc007cd37417df4"`);
        await queryRunner.query(`ALTER TABLE "Load" DROP CONSTRAINT "FK_3fff981cb944e6dff0104b8cf8b"`);
        await queryRunner.query(`ALTER TABLE "Load" DROP CONSTRAINT "FK_d108ea11b35539f91a54fff4f91"`);
        await queryRunner.query(`ALTER TABLE "RouteOption" DROP CONSTRAINT "FK_aba53864339827926b041d92715"`);
        await queryRunner.query(`ALTER TABLE "LoadAssignment" DROP CONSTRAINT "FK_f9ec40a726f805ef9a33fc20c3d"`);
        await queryRunner.query(`ALTER TABLE "LoadAssignment" DROP CONSTRAINT "FK_86c06a2ba28ad050bbeb01cfc80"`);
        await queryRunner.query(`ALTER TABLE "LoadAssignment" DROP CONSTRAINT "FK_3c6b1f40e0d42c86a32b378d026"`);
        await queryRunner.query(`ALTER TABLE "LoadAssignment" DROP CONSTRAINT "FK_c3269a1cf0f0e5919cefa42b991"`);
        await queryRunner.query(`ALTER TABLE "LoadAssignment" DROP CONSTRAINT "FK_07260abdf777176469bcccb8825"`);
        await queryRunner.query(`ALTER TABLE "LoadAssignment" DROP CONSTRAINT "FK_b00dac203c772e475a83f189a8d"`);
        await queryRunner.query(`ALTER TABLE "Trip" DROP CONSTRAINT "FK_9f8994728a83d5a12b21aebfcc6"`);
        await queryRunner.query(`ALTER TABLE "Trip" DROP CONSTRAINT "FK_e6ca78501405de3273030457826"`);
        await queryRunner.query(`ALTER TABLE "Trip" DROP CONSTRAINT "FK_0924c27ba104c6e33a6751c0d9f"`);
        await queryRunner.query(`ALTER TABLE "Trip" DROP CONSTRAINT "FK_45d5e197417fc3cf66f9615fb0c"`);
        await queryRunner.query(`ALTER TABLE "Trip" DROP CONSTRAINT "FK_ca2dc51a970ab5377dfa5da5f03"`);
        await queryRunner.query(`ALTER TABLE "Trip" DROP CONSTRAINT "FK_d434995cd2c77a5f9c71db31cb2"`);
        await queryRunner.query(`ALTER TABLE "TripLocation" DROP CONSTRAINT "FK_4276556f330948872d53a9ca3ea"`);
        await queryRunner.query(`ALTER TABLE "Settlement" DROP CONSTRAINT "FK_9ff72bc80c42b4ba0e50381bbc2"`);
        await queryRunner.query(`ALTER TABLE "Payment" DROP CONSTRAINT "FK_0d14a4ef0d89b5d6f86d79aee5b"`);
        await queryRunner.query(`ALTER TABLE "DeliveryProof" DROP CONSTRAINT "FK_4a901d7b58265327dffe3316f8c"`);
        await queryRunner.query(`ALTER TABLE "Waybill" DROP CONSTRAINT "FK_2049010616662463be4e8de4266"`);
        await queryRunner.query(`ALTER TABLE "LoadingOrder" DROP CONSTRAINT "FK_5062be1d359615a0fe42286912f"`);
        await queryRunner.query(`ALTER TABLE "TripExpense" DROP CONSTRAINT "FK_9f0149e3ffe8caf9461813934c3"`);
        await queryRunner.query(`ALTER TABLE "FuelRecord" DROP CONSTRAINT "FK_649ae27008d8bd334fa9aec183a"`);
        await queryRunner.query(`ALTER TABLE "FuelRecord" DROP CONSTRAINT "FK_a686d07e208488c86f3e29e2cea"`);
        await queryRunner.query(`ALTER TABLE "FuelRecord" DROP CONSTRAINT "FK_0fa3e2d0869c8672f64e89ccff3"`);
        await queryRunner.query(`ALTER TABLE "Route" DROP CONSTRAINT "FK_4845b605fc62b06c30cd1b66c00"`);
        await queryRunner.query(`ALTER TABLE "DriverLoadRequest" DROP CONSTRAINT "FK_6150f6f5b1369ce8cdb01292caa"`);
        await queryRunner.query(`ALTER TABLE "DriverLoadRequest" DROP CONSTRAINT "FK_4bdb6250463f8f2943ad4f0bb87"`);
        await queryRunner.query(`ALTER TABLE "DriverLoadRequest" DROP CONSTRAINT "FK_9052d08be85dfbf0e3da05279cc"`);
        await queryRunner.query(`ALTER TABLE "DriverLoadRequest" DROP CONSTRAINT "FK_b4712d22592c0f5ca74961fc6f3"`);
        await queryRunner.query(`ALTER TABLE "LoadOffer" DROP CONSTRAINT "FK_767b01eba868b762b8c1f976f93"`);
        await queryRunner.query(`ALTER TABLE "LoadOffer" DROP CONSTRAINT "FK_f78aa4d09785066b13cf72fd2bd"`);
        await queryRunner.query(`ALTER TABLE "LoadOffer" DROP CONSTRAINT "FK_c78230559b35bb56b9a2acb7162"`);
        await queryRunner.query(`ALTER TABLE "DriverMatch" DROP CONSTRAINT "FK_931501ef747293149b2872484a1"`);
        await queryRunner.query(`ALTER TABLE "DriverMatch" DROP CONSTRAINT "FK_9173fa974b603c23e1350c09471"`);
        await queryRunner.query(`ALTER TABLE "DriverMatch" DROP CONSTRAINT "FK_69f60292447c83b1585b4c51b25"`);
        await queryRunner.query(`ALTER TABLE "DriverAvailability" DROP CONSTRAINT "FK_451890eae7849347232f474af7b"`);
        await queryRunner.query(`ALTER TABLE "DriverAvailability" DROP CONSTRAINT "FK_24bd372e34986c9b340f9f1cb83"`);
        await queryRunner.query(`ALTER TABLE "DriverAvailability" DROP CONSTRAINT "FK_5b782049bfad845bc9ce5872a32"`);
        await queryRunner.query(`ALTER TABLE "DriverAvailability" DROP CONSTRAINT "FK_b0c2cc6955e4d63d4584f5ca8cf"`);
        await queryRunner.query(`ALTER TABLE "DriverAvailability" DROP CONSTRAINT "FK_00d63c1fba313970a74c6f05469"`);
        await queryRunner.query(`ALTER TABLE "City" DROP CONSTRAINT "FK_bf6142cf9568097619981928455"`);
        await queryRunner.query(`ALTER TABLE "Location" DROP CONSTRAINT "FK_f6238d75218c0fab06615f8aea2"`);
        await queryRunner.query(`ALTER TABLE "Location" DROP CONSTRAINT "FK_fd015fc3b566ce57e00ed4bf845"`);
        await queryRunner.query(`ALTER TABLE "Trailer" DROP CONSTRAINT "FK_30d1aafa22fce283555bccd47e0"`);
        await queryRunner.query(`DROP TABLE "VehicleType"`);
        await queryRunner.query(`DROP TABLE "Vehicle"`);
        await queryRunner.query(`DROP TABLE "DriverVehicle"`);
        await queryRunner.query(`DROP TABLE "Driver"`);
        await queryRunner.query(`DROP TABLE "CompanyDriver"`);
        await queryRunner.query(`DROP TABLE "TransportCompany"`);
        await queryRunner.query(`DROP TABLE "Customer"`);
        await queryRunner.query(`DROP TABLE "TransportRequest"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_16b681b87e374c663c05a5c56b"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_c342add5fa417877b101f4872b"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_cc57638cce12511c5a981f6a00"`);
        await queryRunner.query(`DROP TABLE "Load"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_c37d6d8b80ed3737077db6b09d"`);
        await queryRunner.query(`DROP TABLE "RouteOption"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_0a586efb81f36a43162332521d"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_c65158539f27cb9d4019917614"`);
        await queryRunner.query(`DROP TABLE "LoadAssignment"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_d485417dfe0a2ed5b383df4495"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_e2282ec3b597efae28a86df546"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ca2dc51a970ab5377dfa5da5f0"`);
        await queryRunner.query(`DROP TABLE "Trip"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_faeb841e6500dbfa808f4076d7"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_a24143d1685c49447e32f3e2cf"`);
        await queryRunner.query(`DROP TABLE "TripLocation"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_0bb65bfc6ce2e6838bded045d1"`);
        await queryRunner.query(`DROP TABLE "Settlement"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_b52701997788b3dfbb62a11e3f"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_d2eb0d5d1d98e784a5a29b84ff"`);
        await queryRunner.query(`DROP TABLE "Payment"`);
        await queryRunner.query(`DROP TABLE "DeliveryProof"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_81522ea6b7fac7830f582eb12a"`);
        await queryRunner.query(`DROP TABLE "Waybill"`);
        await queryRunner.query(`DROP TABLE "LoadingOrder"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_8817633a11bea90898724725e2"`);
        await queryRunner.query(`DROP TABLE "TripExpense"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_594d6b815ba86b36358bdb771e"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_e9bb661a8e124fd1b5e4c69296"`);
        await queryRunner.query(`DROP TABLE "FuelRecord"`);
        await queryRunner.query(`DROP TABLE "Route"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_2be8b5209f7ce94de505aad240"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_305b7a04b30de2ebd2cac79320"`);
        await queryRunner.query(`DROP TABLE "DriverLoadRequest"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_54081254b630c4dadd02c57970"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_37a1a3cd1aa890853a4f0791dd"`);
        await queryRunner.query(`DROP TABLE "LoadOffer"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_4f928905db278920a80bea37e9"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_83a87436ed56fb970357a67a82"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_7e54da371cf64b8c816038efbb"`);
        await queryRunner.query(`DROP TABLE "DriverMatch"`);
        await queryRunner.query(`DROP TABLE "CargoType"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_15ba759542bacc2d362babed19"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ed1a46edb0810f93e42cd258a4"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_59d2e870119ad891adb76cb65e"`);
        await queryRunner.query(`DROP TABLE "DriverAvailability"`);
        await queryRunner.query(`DROP TABLE "City"`);
        await queryRunner.query(`DROP TABLE "Province"`);
        await queryRunner.query(`DROP TABLE "Location"`);
        await queryRunner.query(`DROP TABLE "Trailer"`);
        await queryRunner.query(`DROP TABLE "TrailerType"`);
    }

}
